#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'europa:~/bots/world-heritage-twitter-bot/'

ssh europa "\
cd ~/world-heritage-twitter-bot
npm i
npm update
forever-service delete world-heritage-twitter-bot
forever-service install world-heritage-twitter-bot -e 'NODE_ENV=production ENV=production' --start -s index.js"
