#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'enceladus:~/world-heritage-twitter-bot/'

ssh enceladus "\
cd ~/world-heritage-twitter-bot
npm i
npm update
forever stop world-heritage-twitter-bot
export NODE_ENV=production
forever start -a --uid world-heritage-twitter-bot index.js"
